name: Test NTX

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Run test on NTX
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set the input
        uses: ./
        with:
          ntx-url: 'https://reqbin.com/echo/get/json'

      - name: Get the output
        run: echo "The test was ${{ steps.ntx.outputs.status}}"